services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  oracle_db:
    image: gvenzl/oracle-free:latest
    container_name: oracle_container
    environment:
      ORACLE_PASSWORD: my_password
      ORACLE_DATABASE: my_database
      ORACLE_ALLOW_REMOTE: "true"
      APP_USER: my_user
      APP_USER_PASSWORD: my_password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  mysql_data:
  oracle_data:
